apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sentinelstream-hpa
  labels:
    app.kubernetes.io/name: sentinelstream
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sentinelstream-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
