apiVersion: v1
kind: Secret
metadata:
  name: sentinelstream-secrets
  labels:
    app.kubernetes.io/name: sentinelstream
type: Opaque
stringData:
  POSTGRES_USER: "sentinel_user"
  POSTGRES_PASSWORD: "sentinel_secure_pass"
