apiVersion: v1
kind: Service
metadata:
  name: sentinelstream-service
  labels:
    app.kubernetes.io/name: sentinelstream
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http-metrics
  selector:
    app.kubernetes.io/name: sentinelstream
